version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: datashift_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_nova_senha
      POSTGRES_DB: DataShiftDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: